# Generated by Django 5.2.7 on 2026-05-11 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('coding_test', 'Coding Test'), ('second_interview', 'Second Interview'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Optional note about this status change')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='applications.jobapplication')),
            ],
            options={
                'verbose_name_plural': 'Status histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
